{
    "weapons":{
        "1":{
            "name":"iron sword",
            "damage":5
        },
        "2":{
            "name":"infinity sword",
            "damage":999
        },
        "3":{ "name":"bronze dagger", "damage":10 },
        "4":{ "name":"steel sword", "damage":18 },
        "5":{ "name":"silver rapier", "damage":25 },
        "6":{ "name":"battle axe", "damage":32 },
        "7":{ "name":"war hammer", "damage":40 },
        "8":{ "name":"elven blade", "damage":48 },
        "9":{ "name":"orcish cleaver", "damage":56 },
        "10":{ "name":"crystal saber", "damage":64 },
        "11":{ "name":"flame sword", "damage":72 },
        "12":{ "name":"frost axe", "damage":80 },
        "13":{ "name":"shadow dagger", "damage":88 },
        "14":{ "name":"lightning spear", "damage":96 },
        "15":{ "name":"dragon fang", "damage":104 },
        "16":{ "name":"vampire blade", "damage":112 },
        "17":{ "name":"dwarven warhammer", "damage":120 },
        "18":{ "name":"giant's club", "damage":128 },
        "19":{ "name":"serpent whip", "damage":136 },
        "20":{ "name":"phoenix talon", "damage":144 },
        "21":{ "name":"moonlight sword", "damage":152 },
        "22":{ "name":"sunfire blade", "damage":160 },
        "23":{ "name":"storm breaker", "damage":168 },
        "24":{ "name":"void edge", "damage":176 },
        "25":{ "name":"mythril saber", "damage":184 },
        "26":{ "name":"obsidian axe", "damage":192 },
        "27":{ "name":"emerald dagger", "damage":200 },
        "28":{ "name":"ruby sword", "damage":208 },
        "29":{ "name":"sapphire blade", "damage":216 },
        "30":{ "name":"golden scimitar", "damage":224 },
        "31":{ "name":"titanium longsword", "damage":232 },
        "32":{ "name":"demon slayer", "damage":240 },
        "33":{ "name":"angelic rapier", "damage":248 },
        "34":{ "name":"spirit katana", "damage":256 },
        "35":{ "name":"bone crusher", "damage":264 },
        "36":{ "name":"soul reaver", "damage":272 },
        "37":{ "name":"arcane staff", "damage":280 },
        "38":{ "name":"wind cutter", "damage":288 },
        "39":{ "name":"earthshaker", "damage":296 },
        "40":{ "name":"starforged blade", "damage":304 },
        "41":{ "name":"bloodletter", "damage":312 },
        "42":{ "name":"frostmourne", "damage":320 },
        "43":{ "name":"hellfire sword", "damage":328 },
        "44":{ "name":"celestial lance", "damage":336 },
        "45":{ "name":"nightmare blade", "damage":344 },
        "46":{ "name":"reaper's scythe", "damage":352 },
        "47":{ "name":"hydra fang", "damage":360 },
        "48":{ "name":"griffin talon", "damage":368 },
        "49":{ "name":"wyvern claw", "damage":376 },
        "50":{ "name":"thunder axe", "damage":384 },
        "51":{ "name":"tempest blade", "damage":392 },
        "52":{ "name":"avalanche hammer", "damage":400 },
        "53":{ "name":"volcanic sword", "damage":408 },
        "54":{ "name":"spectral saber", "damage":416 },
        "55":{ "name":"phantom dagger", "damage":424 },
        "56":{ "name":"golem fist", "damage":432 },
        "57":{ "name":"basilisk blade", "damage":440 },
        "58":{ "name":"lich staff", "damage":448 },
        "59":{ "name":"paladin's sword", "damage":456 },
        "60":{ "name":"necromancer's scythe", "damage":464 },
        "61":{ "name":"berserker axe", "damage":472 },
        "62":{ "name":"samurai katana", "damage":480 },
        "63":{ "name":"assassin's blade", "damage":488 },
        "64":{ "name":"gladiator's trident", "damage":496 },
        "65":{ "name":"ranger's bow", "damage":504 },
        "66":{ "name":"hunter's spear", "damage":512 },
        "67":{ "name":"pirate cutlass", "damage":520 },
        "68":{ "name":"corsair's sabre", "damage":528 },
        "69":{ "name":"monk's staff", "damage":536 },
        "70":{ "name":"priest's mace", "damage":544 },
        "71":{ "name":"witch's wand", "damage":552 },
        "72":{ "name":"warlock's rod", "damage":560 },
        "73":{ "name":"enchanter's blade", "damage":568 },
        "74":{ "name":"illusionist's dagger", "damage":576 },
        "75":{ "name":"beastmaster's whip", "damage":584 },
        "76":{ "name":"barbarian's club", "damage":592 },
        "77":{ "name":"templar's sword", "damage":600 },
        "78":{ "name":"crusader's flail", "damage":608 },
        "79":{ "name":"oracle's staff", "damage":616 },
        "80":{ "name":"seer blade", "damage":624 },
        "81":{ "name":"prophet's scythe", "damage":632 },
        "82":{ "name":"sage's rod", "damage":640 },
        "83":{ "name":"archmage's staff", "damage":648 },
        "84":{ "name":"sorcerer's wand", "damage":656 },
        "85":{ "name":"alchemist's blade", "damage":664 },
        "86":{ "name":"herbalist's sickle", "damage":672 },
        "87":{ "name":"shaman's club", "damage":680 },
        "88":{ "name":"druid's staff", "damage":688 },
        "89":{ "name":"elementalist's blade", "damage":696 },
        "90":{ "name":"summoner's rod", "damage":704 },
        "91":{ "name":"behemoth axe", "damage":712 },
        "92":{ "name":"leviathan blade", "damage":720 },
        "93":{ "name":"colossus hammer", "damage":728 },
        "94":{ "name":"titan sword", "damage":736 },
        "95":{ "name":"immortal blade", "damage":744 },
        "96":{ "name":"eternal saber", "damage":752 },
        "97":{ "name":"legendary sword", "damage":760 },
        "98":{ "name":"mythic blade", "damage":768 },
        "99":{ "name":"divine sword", "damage":776 },
        "100":{ "name":"cosmic edge", "damage":784 }
    },
    "shields":{
        "101":{
            "name":"leather shield",
            "resistance":5
        },
        "102":{
            "name":"void shield",
            "resistance":999
        },
        "103":{ "name":"wooden buckler", "resistance":12 },
        "104":{ "name":"bronze shield", "resistance":20 },
        "105":{ "name":"iron shield", "resistance":28 },
        "106":{ "name":"steel shield", "resistance":36 },
        "107":{ "name":"tower shield", "resistance":44 },
        "108":{ "name":"spiked shield", "resistance":52 },
        "109":{ "name":"elven guard", "resistance":60 },
        "110":{ "name":"orcish wall", "resistance":68 },
        "111":{ "name":"crystal barrier", "resistance":76 },
        "112":{ "name":"flame ward", "resistance":84 },
        "113":{ "name":"frost guard", "resistance":92 },
        "114":{ "name":"shadow shield", "resistance":100 },
        "115":{ "name":"lightning aegis", "resistance":108 },
        "116":{ "name":"dragon scale", "resistance":116 },
        "117":{ "name":"vampire guard", "resistance":124 },
        "118":{ "name":"dwarven bulwark", "resistance":132 },
        "119":{ "name":"giant's plate", "resistance":140 },
        "120":{ "name":"serpent scale", "resistance":148 },
        "121":{ "name":"phoenix shield", "resistance":156 },
        "122":{ "name":"moonlight barrier", "resistance":164 },
        "123":{ "name":"sunfire shield", "resistance":172 },
        "124":{ "name":"storm wall", "resistance":180 },
        "125":{ "name":"void plate", "resistance":188 },
        "126":{ "name":"mythril guard", "resistance":196 },
        "127":{ "name":"obsidian shield", "resistance":204 },
        "128":{ "name":"emerald guard", "resistance":212 },
        "129":{ "name":"ruby shield", "resistance":220 },
        "130":{ "name":"sapphire barrier", "resistance":228 },
        "131":{ "name":"golden shield", "resistance":236 },
        "132":{ "name":"titanium wall", "resistance":244 },
        "133":{ "name":"demon ward", "resistance":252 },
        "134":{ "name":"angelic aegis", "resistance":260 },
        "135":{ "name":"spirit shield", "resistance":268 },
        "136":{ "name":"bone wall", "resistance":276 },
        "137":{ "name":"soul barrier", "resistance":284 },
        "138":{ "name":"arcane guard", "resistance":292 },
        "139":{ "name":"wind shield", "resistance":300 },
        "140":{ "name":"earth plate", "resistance":308 },
        "141":{ "name":"starforged shield", "resistance":316 },
        "142":{ "name":"bloodguard", "resistance":324 },
        "143":{ "name":"frostplate", "resistance":332 },
        "144":{ "name":"hellfire shield", "resistance":340 },
        "145":{ "name":"celestial wall", "resistance":348 },
        "146":{ "name":"nightmare guard", "resistance":356 },
        "147":{ "name":"reaper's barrier", "resistance":364 },
        "148":{ "name":"hydra scale", "resistance":372 },
        "149":{ "name":"griffin shield", "resistance":380 },
        "150":{ "name":"wyvern plate", "resistance":388 },
        "151":{ "name":"thunder wall", "resistance":396 },
        "152":{ "name":"tempest guard", "resistance":404 },
        "153":{ "name":"avalanche shield", "resistance":412 },
        "154":{ "name":"volcanic plate", "resistance":420 },
        "155":{ "name":"spectral barrier", "resistance":428 },
        "156":{ "name":"phantom guard", "resistance":436 },
        "157":{ "name":"golem plate", "resistance":444 },
        "158":{ "name":"basilisk shield", "resistance":452 },
        "159":{ "name":"lich barrier", "resistance":460 },
        "160":{ "name":"paladin's aegis", "resistance":468 },
        "161":{ "name":"necromancer's wall", "resistance":476 },
        "162":{ "name":"berserker plate", "resistance":484 },
        "163":{ "name":"samurai guard", "resistance":492 },
        "164":{ "name":"assassin's shield", "resistance":500 },
        "165":{ "name":"gladiator's wall", "resistance":508 },
        "166":{ "name":"ranger's guard", "resistance":516 },
        "167":{ "name":"hunter's shield", "resistance":524 },
        "168":{ "name":"pirate's buckler", "resistance":532 },
        "169":{ "name":"corsair's plate", "resistance":540 },
        "170":{ "name":"monk's guard", "resistance":548 },
        "171":{ "name":"priest's barrier", "resistance":556 },
        "172":{ "name":"witch's ward", "resistance":564 },
        "173":{ "name":"warlock's shield", "resistance":572 },
        "174":{ "name":"enchanter's guard", "resistance":580 },
        "175":{ "name":"illusionist's wall", "resistance":588 },
        "176":{ "name":"beastmaster's plate", "resistance":596 },
        "177":{ "name":"barbarian's shield", "resistance":604 },
        "178":{ "name":"templar's aegis", "resistance":612 },
        "179":{ "name":"crusader's wall", "resistance":620 },
        "180":{ "name":"oracle's barrier", "resistance":628 },
        "181":{ "name":"seer guard", "resistance":636 },
        "182":{ "name":"prophet's shield", "resistance":644 },
        "183":{ "name":"sage's plate", "resistance":652 },
        "184":{ "name":"archmage's barrier", "resistance":660 },
        "185":{ "name":"sorcerer's wall", "resistance":668 },
        "186":{ "name":"alchemist's guard", "resistance":676 },
        "187":{ "name":"herbalist's shield", "resistance":684 },
        "188":{ "name":"shaman's plate", "resistance":692 },
        "189":{ "name":"druid's barrier", "resistance":700 },
        "190":{ "name":"elementalist's wall", "resistance":708 },
        "191":{ "name":"summoner's guard", "resistance":716 },
        "192":{ "name":"behemoth plate", "resistance":724 },
        "193":{ "name":"leviathan shield", "resistance":732 },
        "194":{ "name":"colossus wall", "resistance":740 },
        "195":{ "name":"titan plate", "resistance":748 },
        "196":{ "name":"immortal guard", "resistance":756 },
        "197":{ "name":"eternal barrier", "resistance":764 },
        "198":{ "name":"legendary shield", "resistance":772 },
        "199":{ "name":"mythic wall", "resistance":780 },
        "200":{ "name":"divine plate", "resistance":788 }
    },
    "potions":{
        "201":{
            "name":"lesser healing potion",
            "value":15
        },
        "202":{
            "name":"golden potion",
            "value":999
        },
        "203":{ "name":"minor healing potion", "value":25 },
        "204":{ "name":"standard healing potion", "value":35 },
        "205":{ "name":"greater healing potion", "value":45 },
        "206":{ "name":"superior healing potion", "value":55 },
        "207":{ "name":"elixir of health", "value":65 },
        "208":{ "name":"vitality draught", "value":75 },
        "209":{ "name":"elven tonic", "value":85 },
        "210":{ "name":"orcish brew", "value":95 },
        "211":{ "name":"crystal elixir", "value":105 },
        "212":{ "name":"flame potion", "value":115 },
        "213":{ "name":"frost potion", "value":125 },
        "214":{ "name":"shadow elixir", "value":135 },
        "215":{ "name":"lightning tonic", "value":145 },
        "216":{ "name":"dragon's blood", "value":155 },
        "217":{ "name":"vampire serum", "value":165 },
        "218":{ "name":"dwarven ale", "value":175 },
        "219":{ "name":"giant's tonic", "value":185 },
        "220":{ "name":"serpent venom", "value":195 },
        "221":{ "name":"phoenix essence", "value":205 },
        "222":{ "name":"moonlight elixir", "value":215 },
        "223":{ "name":"sunfire potion", "value":225 },
        "224":{ "name":"storm draught", "value":235 },
        "225":{ "name":"void elixir", "value":245 },
        "226":{ "name":"mythril tonic", "value":255 },
        "227":{ "name":"obsidian potion", "value":265 },
        "228":{ "name":"emerald elixir", "value":275 },
        "229":{ "name":"ruby potion", "value":285 },
        "230":{ "name":"sapphire tonic", "value":295 },
        "231":{ "name":"golden elixir", "value":305 },
        "232":{ "name":"titanium draught", "value":315 },
        "233":{ "name":"demon's brew", "value":325 },
        "234":{ "name":"angelic potion", "value":335 },
        "235":{ "name":"spirit elixir", "value":345 },
        "236":{ "name":"bone tonic", "value":355 },
        "237":{ "name":"soul draught", "value":365 },
        "238":{ "name":"arcane potion", "value":375 },
        "239":{ "name":"wind elixir", "value":385 },
        "240":{ "name":"earth tonic", "value":395 },
        "241":{ "name":"starforged potion", "value":405 },
        "242":{ "name":"blood elixir", "value":415 },
        "243":{ "name":"frostmourne draught", "value":425 },
        "244":{ "name":"hellfire potion", "value":435 },
        "245":{ "name":"celestial elixir", "value":445 },
        "246":{ "name":"nightmare tonic", "value":455 },
        "247":{ "name":"reaper's draught", "value":465 },
        "248":{ "name":"hydra venom", "value":475 },
        "249":{ "name":"griffin feather potion", "value":485 },
        "250":{ "name":"wyvern scale elixir", "value":495 },
        "251":{ "name":"thunder potion", "value":505 },
        "252":{ "name":"tempest tonic", "value":515 },
        "253":{ "name":"avalanche draught", "value":525 },
        "254":{ "name":"volcanic elixir", "value":535 },
        "255":{ "name":"spectral potion", "value":545 },
        "256":{ "name":"phantom tonic", "value":555 },
        "257":{ "name":"golem dust potion", "value":565 },
        "258":{ "name":"basilisk venom", "value":575 },
        "259":{ "name":"lich elixir", "value":585 },
        "260":{ "name":"paladin's draught", "value":595 },
        "261":{ "name":"necromancer's potion", "value":605 },
        "262":{ "name":"berserker's tonic", "value":615 },
        "263":{ "name":"samurai elixir", "value":625 },
        "264":{ "name":"assassin's draught", "value":635 },
        "265":{ "name":"gladiator's potion", "value":645 },
        "266":{ "name":"ranger's tonic", "value":655 },
        "267":{ "name":"hunter's elixir", "value":665 },
        "268":{ "name":"pirate's brew", "value":675 },
        "269":{ "name":"corsair's potion", "value":685 },
        "270":{ "name":"monk's tonic", "value":695 },
        "271":{ "name":"priest's elixir", "value":705 },
        "272":{ "name":"witch's potion", "value":715 },
        "273":{ "name":"warlock's draught", "value":725 },
        "274":{ "name":"enchanter's elixir", "value":735 },
        "275":{ "name":"illusionist's potion", "value":745 },
        "276":{ "name":"beastmaster's tonic", "value":755 },
        "277":{ "name":"barbarian's brew", "value":765 },
        "278":{ "name":"templar's elixir", "value":775 },
        "279":{ "name":"crusader's potion", "value":785 },
        "280":{ "name":"oracle's draught", "value":795 },
        "281":{ "name":"seer elixir", "value":805 },
        "282":{ "name":"prophet's potion", "value":815 },
        "283":{ "name":"sage's tonic", "value":825 },
        "284":{ "name":"archmage's elixir", "value":835 },
        "285":{ "name":"sorcerer's potion", "value":845 },
        "286":{ "name":"alchemist's draught", "value":855 },
        "287":{ "name":"herbalist's elixir", "value":865 },
        "288":{ "name":"shaman's potion", "value":875 },
        "289":{ "name":"druid's tonic", "value":885 },
        "290":{ "name":"elementalist's elixir", "value":895 },
        "291":{ "name":"summoner's potion", "value":905 },
        "292":{ "name":"behemoth's draught", "value":915 },
        "293":{ "name":"leviathan's elixir", "value":925 },
        "294":{ "name":"colossus potion", "value":935 },
        "295":{ "name":"titan's tonic", "value":945 },
        "296":{ "name":"immortal elixir", "value":955 },
        "297":{ "name":"eternal potion", "value":965 },
        "298":{ "name":"legendary draught", "value":975 },
        "299":{ "name":"mythic elixir", "value":985 },
        "300":{ "name":"divine potion", "value":995 }
    }
}